### ISSUE TITLE
Create frontend skeleton

### ISSUE THREAD

**Issue by Jaden51** [ubcesports/lounge-hub#25]
**Task**
Follow the [activity diagram](https://drive.google.com/file/d/1NafpR3f9rx_gNVrslSm5JHVtw2JR0Xdy/view?usp=sharing) of the behaviour of the lounge-hub. Create the necessary frontend components needed to support this. There will be no styling, this issue is only for creating the necessary layout to interact with the backend. 

This will mostly include:
- Routing
- Pages

**Comment by Kevinxygu** [comment]
[Figma link is here](https://www.figma.com/design/LmsxQqR1p1iCC7pL3o1hJ2/UBCEA-Lounge-App?node-id=0-1&t=BI5Ss20p56gvYKmL-1)

[Prototype screen recording link is here](https://youtu.be/Qial96ZNRL0)

Use cases + User stories:
1. Login
2. View status of single desk (Open, Busy, Closed) and perform actions on it (reserve open desk, free busy desk, close a desk, released a closed desk). Closed desks are for when the PC doesn't work
3. Sign in someone with their student number, game, table number
4. View student's information
5. Add a new student
6. View all student records and perform actions on them. Also, forgot that we won't be deleting someone so that functionality can be ignored
7. View activity log of desk bookings
8. Filter student records
9. Export activity log to CSV feature is pending: Depends on chat with IR

OTHER NOTES:
1. since it's on desktop, i don't see us adding any reactivity to it
2. the screen recording captured some weird colours + rendering; the real colours are all on the Figma
3. UI inspired by Tesla UI + Spotify

**Comment by joshhwuu** [comment]
oh good heavens this looks insane bless you @Kevinxygu

**Comment by Kevinxygu** [comment]
LOLLLL thank you @joshhwuu
